name: Pull Request

# on:
#   pull_request:
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  run_pull_request_checks:
    runs-on: ubuntu-latest
    steps:
      # Verify if there are no broken links in PR
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
        with:        
          use-verbose-mode: 'yes'