name: Pull Request

# on:
#   pull_request:
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  docs_check:
    name: Perform quality checks on the docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify if there are no broken links in the docs
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
        with:        
          use-verbose-mode: 'yes'

  build:
    name: Build all arduino samples
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile all Arduino samples for the ATtiny3216
      uses: ArminJo/arduino-test-compile@v2
      with:
        arduino-board-fqbn: megaTinyCore:megaavr:atxy6:chip=3216,clock=20,bodvoltage=4v2,bodmodeactive=disabled,bodmodesleep=disabled,eesave=enable,millis=enabled,uartvoltage=5v
        platform-url: http://drazzy.com/package_drazzy.com_index.json
