name: Pull Request

# on:
#   pull_request:
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  docs_check:
    name: Perform quality checks on the docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify if there are no broken links in the docs
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
        with:        
          use-verbose-mode: 'yes'

  build:
    name: Build all arduino samples
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2
      # with:
      #   arduino-board-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
      #   platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
      #   required-libraries: Servo,Adafruit NeoPixel
      #   sketches-exclude: WhistleSwitch 50Hz
      #   build-properties: '{ "WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'